spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          username: zqs146
          password: zqs15730530530
          uri: https://github.com/zqs146/configserver.git
eureka:
  client:
    service-url:
      defaultZone: http://xmccjyqs.com:7001/eureka/ #,http://xmccjyqs.com:7002/eureka/