server:
  port: 8800

spring:
  application:
    name: mq-consumer
  rabbitmq:
    host: 192.168.1.105
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://xmccjyqs.com:7001/eureka/
